/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { BsFillEmojiSunglassesFill, BsSearch } from 'react-icons/bs'
export default function Home() {
  // console.log(bg_video)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <section className='w-full h-full flex flex-col items-center py-7 bg-[#0000004f]'>
          {/* logo website  */}

          <h1 className={styles.logo}><BsFillEmojiSunglassesFill className='mb-2'/> MR.WatherApp</h1>

          {/* search location  form  */}
          <form className='w-full '>
            <div className='w-[60%] mx-auto relative'>
              <input type="text" placeholder='Search your location' className='p-3 px-8 w-full rounded-full font-bold' />
              <button className='absolute flex justify-center items-center right-3 top-[50%] translate-y-[-50%] bg-gray-300 transition-all hover:bg-gray-600 hover:text-white p-2 rounded-full px-7'>
                <BsSearch className='text-xl'/>
              </button>
            </div>
          </form>
        </section>
      </main>
    </>
  )
}
